Repository DaniW42/motioneye-telegram, pull requests merged in 2020-08, with the labels that each got.

#11 update to use @jsondumpbot to get chat id
  README.md
Labels: enhancement

#14 fixed ip address update in config
  COPYRIGHT.md
  README.md
  bin/motion-send.sh
  install-tg.sh
Labels: Hacktoberfest

#12 Merge Testing to Master
  COPYRIGHT.md
  README.md
  bin/git-updatecheck.sh
  bin/motion-send.sh
  bin/presencecheck.sh
  install-cron.sh
  install-tg.sh
  telegram.conf.original
Labels: Hacktoberfest, enhancement
